--Player table creation
DROP TABLE Player

CREATE TABLE Player(
	id int primary key NOT NULL, player_api_id int NOT NULL, player_name nvarchar(50) NOT NULL, player_fifa_api_id varchar(100) NOT NULL, birthday datetime2 (7) NOT NULL,
	height float,
	weight int);

--Country table creation
DROP TABLE Country

CREATE TABLE Country (id int foreign key references Player(id) NOT NULL, name char(100));

--League table creation
DROP TABLE League
CREATE TABLE League (id int foreign key references Player(id) NOT NULL, country_id varchar(20), name char(200));

/* Player Attributes Table */

DROP TABLE Player_Attributes

CREATE TABLE Player_Attributes (
id int CONSTRAINT PK_Player_Attributes PRIMARY KEY,
player_fifa_api_id int NOT NULL,
player_api_id int NOT NULL,
date datetime NOT NULL,
overall_rating int NULL,
potential int NULL,
preferred_foot varchar(5) NULL,
attacking_work_rate varchar(6) NULL,
defensive_work_rate varchar(7) NULL,
crossing int NULL,
finishing int NULL,
heading_accuracy int NULL,
short_passing int NULL,
volleys int NULL,
dribbling int NULL,
curve int NULL,
free_kick_accuracy int NULL,
long_passing int NULL,
ball_control int NULL,
acceleration int NULL,
sprint_speed int NULL,
agility int NULL,
reactions int NULL,
balance int NULL,
shot_power int NULL,
jumping int NULL,
stamina int NULL,
strength int NULL,
long_shots int NULL,
aggression int NULL,
interceptions int NULL,
positioning int NULL,
vision int NULL,
penalties int NULL,
marking int NULL,
standing_tackle int NULL,
sliding_tackle int NULL,
gk_diving int NULL,
gk_handling int NULL,
gk_kicking int NULL,
gk_positioning int NULL,
gk_reflexes int NULL
)

--Match table
CREATE TABLE [dbo].[Match](
	[id] [int] NOT NULL,
	[country_id] [int] NOT NULL,
	[league_id] [int] NOT NULL,
	[season] [nvarchar](50) NOT NULL,
	[stage] [int] NOT NULL,
	[date] [date] NOT NULL,
	[match_api_id] [int] NOT NULL,
	[home_team_api_id] [int] NOT NULL,
	[away_team_api_id] [int] NOT NULL,
	[home_team_goal] [int] NOT NULL,
	[away_team_goal] [int] NOT NULL,
	[home_player_X1] [nvarchar](50) NULL,
	[home_player_X2] [nvarchar](50) NULL,
	[home_player_X3] [nvarchar](50) NULL,
	[home_player_X4] [nvarchar](50) NULL,
	[home_player_X5] [nvarchar](50) NULL,
	[home_player_X6] [nvarchar](50) NULL,
	[home_player_X7] [nvarchar](50) NULL,
	[home_player_X8] [nvarchar](50) NULL,
	[home_player_X9] [nvarchar](50) NULL,
	[home_player_X10] [nvarchar](50) NULL,
	[home_player_X11] [nvarchar](50) NULL,
	[away_player_X1] [nvarchar](50) NULL,
	[away_player_X2] [nvarchar](50) NULL,
	[away_player_X3] [nvarchar](50) NULL,
	[away_player_X4] [nvarchar](50) NULL,
	[away_player_X5] [nvarchar](50) NULL,
	[away_player_X6] [nvarchar](50) NULL,
	[away_player_X7] [nvarchar](50) NULL,
	[away_player_X8] [nvarchar](50) NULL,
	[away_player_X9] [nvarchar](50) NULL,
	[away_player_X10] [nvarchar](50) NULL,
	[away_player_X11] [nvarchar](50) NULL,
	[home_player_Y1] [nvarchar](50) NULL,
	[home_player_Y2] [nvarchar](50) NULL,
	[home_player_Y3] [nvarchar](50) NULL,
	[home_player_Y4] [nvarchar](50) NULL,
	[home_player_Y5] [nvarchar](50) NULL,
	[home_player_Y6] [nvarchar](50) NULL,
	[home_player_Y7] [nvarchar](50) NULL,
	[home_player_Y8] [nvarchar](50) NULL,
	[home_player_Y9] [nvarchar](50) NULL,
	[home_player_Y10] [nvarchar](50) NULL,
	[home_player_Y11] [nvarchar](50) NULL,
	[away_player_Y1] [nvarchar](50) NULL,
	[away_player_Y2] [nvarchar](50) NULL,
	[away_player_Y3] [nvarchar](50) NULL,
	[away_player_Y4] [nvarchar](50) NULL,
	[away_player_Y5] [nvarchar](50) NULL,
	[away_player_Y6] [nvarchar](50) NULL,
	[away_player_Y7] [nvarchar](50) NULL,
	[away_player_Y8] [nvarchar](50) NULL,
	[away_player_Y9] [nvarchar](50) NULL,
	[away_player_Y10] [nvarchar](50) NULL,
	[away_player_Y11] [nvarchar](50) NULL,
	[home_player_1] [nvarchar](50) NULL,
	[home_player_2] [nvarchar](50) NULL,
	[home_player_3] [nvarchar](50) NULL,
	[home_player_4] [nvarchar](50) NULL,
	[home_player_5] [nvarchar](50) NULL,
	[home_player_6] [nvarchar](50) NULL,
	[home_player_7] [nvarchar](50) NULL,
	[home_player_8] [nvarchar](50) NULL,
	[home_player_9] [nvarchar](50) NULL,
	[home_player_10] [nvarchar](50) NULL,
	[home_player_11] [nvarchar](50) NULL,
	[away_player_1] [nvarchar](50) NULL,
	[away_player_2] [nvarchar](50) NULL,
	[away_player_3] [nvarchar](50) NULL,
	[away_player_4] [nvarchar](50) NULL,
	[away_player_5] [nvarchar](50) NULL,
	[away_player_6] [nvarchar](50) NULL,
	[away_player_7] [nvarchar](50) NULL,
	[away_player_8] [nvarchar](50) NULL,
	[away_player_9] [nvarchar](50) NULL,
	[away_player_10] [nvarchar](50) NULL,
	[away_player_11] [nvarchar](50) NULL,
	[goal] [varchar](max) NULL,
	[shoton] [varchar](max) NULL,
	[shotoff] [varchar](max) NULL,
	[foulcommit] [varchar](max) NULL,
	[card] [varchar](max) NULL,
	[cross] [varchar](max) NULL,
	[corner] [varchar](max) NULL,
	[possession] [varchar](max) NULL,
	[B365H] [float] NULL,
	[B365D] [float] NULL,
	[B365A] [float] NULL,
	[BWH] [float] NULL,
	[BWD] [float] NULL,
	[BWA] [float] NULL,
	[IWH] [float] NULL,
	[IWD] [float] NULL,
	[IWA] [float] NULL,
	[LBH] [float] NULL,
	[LBD] [float] NULL,
	[LBA] [float] NULL,
	[PSH] [nvarchar](50) NULL,
	[PSD] [nvarchar](50) NULL,
	[PSA] [nvarchar](50) NULL,
	[WHH] [float] NULL,
	[WHD] [float] NULL,
	[WHA] [float] NULL,
	[SJH] [float] NULL,
	[SJD] [float] NULL,
	[SJA] [float] NULL,
	[VCH] [float] NULL,
	[VCD] [float] NULL,
	[VCA] [float] NULL,
	[GBH] [float] NULL,
	[GBD] [float] NULL,
	[GBA] [float] NULL,
	[BSH] [float] NULL,
	[BSD] [float] NULL,
	[BSA] [float] NULL,
 CONSTRAINT [PK_Match] PRIMARY KEY CLUSTERED)

 --Team Table
 DROP TABLE Team

CREATE TABLE [dbo].[Team](
	[id] [int] NOT NULL,
	[team_api_id] [int] NOT NULL,
	[team_fifa_api_id] [int] NULL,
	[team_long_name] [nvarchar](50) NULL,
	[team_short_name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Team2] PRIMARY KEY CLUSTERED)

 --Team Attributes
 DROP TABLE Team_Attributes

CREATE TABLE [dbo].[Team_Attributes](
	[id] [int] NOT NULL,
	[team_fifa_api_id] [int] NOT NULL,
	[team_api_id] [int] NOT NULL,
	[date] [nvarchar](50) NOT NULL,
	[buildUpPlaySpeed] [int] NOT NULL,
	[buildUpPlaySpeedClass] [nvarchar](50) NOT NULL,
	[buildUpPlayDribbling] [nvarchar](50) NULL,
	[buildUpPlayDribblingClass] [nvarchar](50) NOT NULL,
	[buildUpPlayPassing] [int] NOT NULL,
	[buildUpPlayPassingClass] [nvarchar](50) NOT NULL,
	[buildUpPlayPositioningClass] [nvarchar](50) NOT NULL,
	[chanceCreationPassing] [int] NOT NULL,
	[chanceCreationPassingClass] [nvarchar](50) NOT NULL,
	[chanceCreationCrossing] [int] NOT NULL,
	[chanceCreationCrossingClass] [nvarchar](50) NOT NULL,
	[chanceCreationShooting] [int] NOT NULL,
	[chanceCreationShootingClass] [nvarchar](50) NOT NULL,
	[chanceCreationPositioningClass] [nvarchar](50) NOT NULL,
	[defencePressure] [int] NOT NULL,
	[defencePressureClass] [nvarchar](50) NOT NULL,
	[defenceAggression] [int] NOT NULL,
	[defenceAggressionClass] [nvarchar](50) NOT NULL,
	[defenceTeamWidth] [int] NOT NULL,
	[defenceTeamWidthClass] [nvarchar](50) NOT NULL,
	[defenceDefenderLineClass] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Team_Attributes2] PRIMARY KEY CLUSTERED)



